### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by gclm** [deepjia/v2net#2]
大佬出一个写一个使用教程文档可好 

要不是懂点代理的东西我感觉我就用不成咱这个软件 ，
但是小弟水平有限，说实话有些设置看不懂

是否可以麻烦大佬写一个使用教程   中英文都可以

**Comment by deepjia** [comment]
请参考 README.md
因为还是个 alpha 版本，暂不提供更详细的文档。
这也是配置文件仍设定在 app 包内、且不提供自动更新的原因。
